#!/usr/bin/env python

import argparse

from punch import punch_config as cfr
from punch import file_updater as fu

parser = argparse.ArgumentParser(description="Manages file content with versions.")
parser.add_argument('-c', '--config-file', action='store',
                    help="Config file", default="punch_config.py")
parser.add_argument('-v', '--version-file', action='store',
                    help="Version file", default="punch_version.py")
parser.add_argument('--verbose', action='store_true',
                    help="Be verbose")

args = parser.parse_args()

print("## Punch")

config = cfr.PunchConfig(args.config_file, args.version_file)


print(config.__config_version__)
print(config.globals)
print(config.files)
print(config.version)

# for file_configuration in config.files:
#     updater = fu.FileUpdater(file_configuration)
#     updater.update(current_version, new_version)